apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-exporter
  namespace: monitoring  # Set to 'monitoring' namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowflake-exporter
  template:
    metadata:
      labels:
        app: snowflake-exporter
    spec:
      imagePullSecrets:
        - name: credential
      containers:
        - name: exporter
          image: snowflake-exporter:v2
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: snowflake-secret
            - configMapRef:
                name: snowflake-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"